### PR TITLE
Adapter superclass

### PR DESCRIPTION
**Pull request by aaronwolen**
This creates a new `Adapter` parent class that's inherited by `CrulAdapter` and `HttrAdapter`, consolidating most of the code that was previously duplicated across the two original classes.

It also breaks out some of the tasks performed by `handle_request()` into separate (private) methods. 

It's a work in progress and there are number of decisions that need to be made before it can be finalized, but first I wanted to get your feedback on the general approach.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @aaronwolen - having a look

(does this address #86 at all?)

**Comment by aaronwolen** [comment]
No, since #86 requires tweaking some of the logic for handling requests and the diffs for this PR are so big, I thought it best to save that for a separate PR (those changes are in a separate (and now outdated) [branch](https://github.com/aaronwolen/webmockr/tree/adapter-superclass-fix-86). 

Also, the tests are failing because my original branch was missing the commits added on the 20th. I rebased but missed some of the changes, so I'll have to add those back in.

**Comment by sckott** [comment]
thanks, AFAICT there's no changes other than re-arranging the various methods into a superclass Adapter, and CrulAdapter and HttrAdapter inheriting from Adapter, yeah? 

I'll wait until you add the commits on master, and then test with vcr and other pkgs that depend on webmockr and vcr

**Comment by sckott** [comment]
I like the general approach, it's great to reduce duplicated code, and will make it easier to add an adapter for another http library as they inevitably come down the road

**Comment by aaronwolen** [comment]
> AFAICT there's no changes other than re-arranging the various methods into a superclass Adapter

Right, I really tried to limit the changes here to just consolidating and reorganizing. So everything _should_ function identically but using less code.  

> I like the general approach, it's great to reduce duplicated code

Cool. The goal was to make debugging/development a little easier going forward. I wanted to contribute a few small fixes for some minor issues I ran into w/ osfr and kept forgetting to patch both adapters.

Question for you: do you think `Adapter` should be exported? It's basically useless to the user but it provides a logical location to consolidate documentation for the various adapters.

**Comment by sckott** [comment]
Sounds good. 

I don't see a way around not exporting `Adapter`, since it's nice to have is internal methods documented and such.

**Comment by aaronwolen** [comment]
I tweaked `enable()`/`disable()` to use the new `$client` field and restored the original camel case adapter names. Also verified vcr v0.4.1.93's tests pass with this version of webmockr so I believe it's ready to go.

**Comment by sckott** [comment]
thanks @aaronwolen - looks good to me 

thanks for thes changes

**Pull request merged**
