### PR TITLE
Support crul and httr requests with JSON-encoded bodies

### PR DESCRIPTION
**Pull request by aaronwolen**
This fixes the retrieval of request bodies when they're JSON-encoded.

## Example

Requests with a JSON-encoded body would fail using either `crul` or `httr`, e.g.:

``` r
library(webmockr)
library(httr)
enable()
#> CrulAdapter enabled!
#> HttrAdapter enabled!

url <- "https://httpbin.org/post"
body <- list(foo = "bar")

enable()
#> CrulAdapter enabled!
#> HttrAdapter enabled!

# empty body, no problem
aa <- stub_request("post", uri = url)
POST(url, body = list(foo = "bar"))
#> Response [https://httpbin.org/post]
#>   Date: 2019-12-13 14:09
#>   Status: 200
#>   Content-Type: <unknown>
#> <EMPTY BODY>

# list bodies work as expected
stub_registry_clear()
bb <- stub_request("post", uri = url) %>% wi_th(body = list(foo = "bar"))
POST(url, body = list(foo = "bar"))
#> Response [https://httpbin.org/post]
#>   Date: 2019-12-13 14:09
#>   Status: 200
#>   Content-Type: <unknown>
#> <EMPTY BODY>

# but json-encoding fails
stub_registry_clear()
json_body <- jsonlite::toJSON(body, auto_unbox = TRUE)
cc <- stub_request("post", uri = url) %>% wi_th(body = json_body)
POST(url, body = list(foo = "bar"), encode = "json")
#> Error in if (request_is_in_cache(request_signature)) {: missing value where TRUE/FALSE needed

disable()
#> CrulAdapter disabled!
#> HttrAdapter disabled!
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Description

It looks like you already encountered and solved this problem w/ vcr, so I copied over your fix (`pluck_body()`) to here and use that to retrieve the request body from both adapters.

### CODE REVIEW

**Comment by aaronwolen** [comment]
One thing I wasn't able to grok is when/if you'd want `pluck_body()` to return `FALSE` rather than `NULL` if the body is empty.

**Comment by sckott** [comment]
thanks!  having a look

**Comment by aaronwolen** [comment]
`pluck_body()` is now exported for use w/ vcr. I also reworked it a bit in an attempt to spell out the the assertions and returns.

Also, the revised version of `pluck_body()` will return only `NULL` or the request body, whereas the [original implementation](https://github.com/ropensci/vcr/blob/296ced5bdade62ba418e62d5aa9143a4d79f841c/R/request_handler.R#L210-L217) would return `FALSE` if both `x$fields` and `x$options$postfieldsize` were `NULL`, leading webmockr to believe the body was not empty. 

This only surfaced during testing, and I don't think it could actually happen in the wild because both crul and httr initialize `postfieldsize` as an integer equal to the length of the `body`. Still, I wanted to run this by you and make sure there isn't a scenario I'm overlooking in which this could occur and `pluck_body()` should return `FALSE`.

**Comment by sckott** [comment]
thanks @aaronwolen ! I'll have a look

**Comment by sckott** [comment]
looks good so far. Could you add a test file in tests/ for `pluck_body`?

And seems like it makes sense for https://github.com/ropensci/vcr/pull/130 to use the version of webmockr in this PR? - I guess just need to use `webmockr::pluc_body` and remove `pluck_body` from vcr

**Comment by sckott** [comment]
thanks for all your work on this!

**Comment by aaronwolen** [comment]
NP! Thanks for providing such a rad package. I can't wait to get it setup with osfr—I've been dealing with tests that take ~20min to run for wayyyy too long.

**Comment by sckott** [comment]
Oof, that is a looooong time

**Comment by aaronwolen** [comment]
This lady stops by every time I run the tests:

**Pull request merged**
